version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception
  nginx:
    container_name: nginx
    image: nginx
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        CERTS_CRT: ${CERTS_CRT}
        CERTS_KEY: ${CERTS_KEY}
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress-volume:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
  wordpress:
    container_name: wordpress
    image: wordpress
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        WP_HOST: ${WP_HOST}
    restart: always
    volumes:
      - wordpress-volume:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb

networks:
  inception:
    name: inception

volumes:
  mariadb-volume:
    name: mariadb-volume
    driver: local
    driver_opts:
      type: volume
      device: /home/aminoru-/data/mariadb
      o: bind
  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: volume
      device: /home/aminoru-/data/wordpress
      o: bind